server:
  port: 8081
spring:
  profiles:
    active: native
  application:
    name: USER
  zipkin:
    base-url: http://127.0.0.1:9411/
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://alterra-academy.ceuplinqqmmu.us-east-1.rds.amazonaws.com:3306/userservice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Gd7)xUs0W37Uq[
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': true
jasypt:
  encryptor:
    password: secret
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  file:
    name: logs/user.log
    max-size: 10MB
    max-history: 365
  level:
    root: INFO
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
management:
  endpoints:
    web:
      base-path: /act
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true